ALTER TABLE courses
    ADD COLUMN IF NOT EXISTS expiry_period_type VARCHAR(30) NOT NULL DEFAULT 'LIFETIME';

ALTER TABLE courses
    ADD COLUMN IF NOT EXISTS drip_content BOOLEAN NOT NULL DEFAULT FALSE;
