ALTER TABLE biometric_policies ADD COLUMN local_monitoring_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE proctoring_events DROP CONSTRAINT IF EXISTS ck_proctoring_event_type;
ALTER TABLE proctoring_events ADD CONSTRAINT ck_proctoring_event_type CHECK (type IN (
    'SESSION_STARTED', 'SESSION_ENDED', 'CAMERA_STARTED', 'CAMERA_STOPPED',
    'CAMERA_PERMISSION_DENIED', 'TAB_HIDDEN', 'TAB_VISIBLE', 'WINDOW_BLURRED',
    'WINDOW_FOCUSED', 'NETWORK_OFFLINE', 'NETWORK_ONLINE', 'HEARTBEAT', 'PAGE_EXIT',
    'MICROPHONE_STARTED', 'MICROPHONE_STOPPED', 'MICROPHONE_PERMISSION_DENIED',
    'AUDIO_ACTIVITY', 'FACE_NOT_VISIBLE', 'MULTIPLE_FACES', 'HEAD_TURNED',
    'VISUAL_ANALYSIS_UNAVAILABLE'
));
