import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, CalendarDays, Pencil, Plus, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/auth-context";
import { useToast } from "@/hooks/use-toast";
import { hasAuthority } from "@/lib/rbac-api";
import { assessmentLeaveApi, assessmentLeaveDays, assessmentLeaveInputError, type AssessmentLeaveEvidence, type AssessmentLeavePurpose, type SaveAssessmentLeaveEvidenceInput } from "@/services/api/assessment-leave-api";

const localDate = (date = new Date()) => { const copy = new Date(date); copy.setMinutes(copy.getMinutes() - copy.getTimezoneOffset()); return copy.toISOString().slice(0, 10); };
const currentYear = () => { const d = new Date(); const first = d.getMonth() >= 8 ? d.getFullYear() : d.getFullYear() - 1; return `${first}-${first + 1}`; };
const initialForm = (): SaveAssessmentLeaveEvidenceInput => { const start = new Date(); const end = new Date(start); end.setDate(end.getDate() + 14); return { studentId: 0, academicYear: currentYear(), leavePurpose: "SEMESTER_FINAL_ASSESSMENT", assessmentReference: "", employerName: "", jobTitle: "", employmentDocumentReference: "", leaveOrderNumber: "", leaveOrderDate: localDate(), leaveStartDate: localDate(start), leaveEndDate: localDate(end), salaryRetentionConfirmed: false, evidenceReference: "" }; };
const purposeLabel: Record<AssessmentLeavePurpose, string> = { SEMESTER_FINAL_ASSESSMENT: "Semestr yakuniy baholashi", STATE_ATTESTATION: "Davlat attestatsiyasi", BACHELOR_THESIS_DEFENSE: "Bitiruv malakaviy ishi himoyasi", MASTER_THESIS_DEFENSE: "Magistrlik ishi himoyasi" };

export function AdminAssessmentLeaves() {
  const { user } = useAuth(); const canWrite = hasAuthority(user, "ACADEMIC_WRITE"); const { toast } = useToast(); const client = useQueryClient();
  const [form, setForm] = useState<SaveAssessmentLeaveEvidenceInput>(initialForm); const [editingId, setEditingId] = useState<number | null>(null);
  const [reviewing, setReviewing] = useState<AssessmentLeaveEvidence | null>(null); const [reviewMode, setReviewMode] = useState<"verify" | "reject">("verify"); const [reviewText, setReviewText] = useState("");
  const records = useQuery({ queryKey: ["assessment-leaves"], queryFn: assessmentLeaveApi.list });
  const students = useQuery({ queryKey: ["assessment-leaves", "eligible-students"], queryFn: assessmentLeaveApi.eligibleStudents, enabled: canWrite });
  const refresh = () => client.invalidateQueries({ queryKey: ["assessment-leaves"] });
  const fail = (error: Error) => toast({ variant: "destructive", title: "Amal bajarilmadi", description: error.message });
  const save = useMutation({ mutationFn: () => editingId ? assessmentLeaveApi.update(editingId, form) : assessmentLeaveApi.create(form), onSuccess: async () => { setEditingId(null); setForm(initialForm()); await refresh(); toast({ title: "Ta'til dalili qoralamasi saqlandi" }); }, onError: fail });
  const review = useMutation({ mutationFn: () => reviewMode === "verify" ? assessmentLeaveApi.verify(reviewing!.id, reviewText) : assessmentLeaveApi.reject(reviewing!.id, reviewText), onSuccess: async () => { setReviewing(null); setReviewText(""); await refresh(); toast({ title: "Ta'til dalili holati yangilandi" }); }, onError: fail });
  const openReview = (record: AssessmentLeaveEvidence, mode: "verify" | "reject") => { setReviewing(record); setReviewMode(mode); setReviewText(""); };
  const edit = (record: AssessmentLeaveEvidence) => { setEditingId(record.id); setForm({ studentId: record.studentId, academicYear: record.academicYear, leavePurpose: record.leavePurpose, assessmentReference: record.assessmentReference, employerName: record.employerName, jobTitle: record.jobTitle, employmentDocumentReference: record.employmentDocumentReference, leaveOrderNumber: record.leaveOrderNumber, leaveOrderDate: record.leaveOrderDate, leaveStartDate: record.leaveStartDate, leaveEndDate: record.leaveEndDate, salaryRetentionConfirmed: record.salaryRetentionConfirmed, evidenceReference: record.evidenceReference }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const error = assessmentLeaveInputError(form); const days = assessmentLeaveDays(form.leaveStartDate, form.leaveEndDate);

  return <div className="space-y-6 p-3 sm:p-6">
    <div><h1 className="text-2xl font-bold">Yakuniy baholash ta'tili</h1><p className="text-sm text-muted-foreground">559-son qaror 22-bandi: ishlaydigan masofaviy talaba uchun kamida 15 kalendar kun ish haqi saqlangan ta'til dalili.</p></div>
    {canWrite && <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5" />{editingId ? "Qoralamani tahrirlash" : "Ish beruvchi ta'til dalili"}</CardTitle><CardDescription>Mehnat faoliyati, baholash maqsadi, ish beruvchi buyrug'i va himoyalangan dalil rekviziti birga saqlanadi.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">
      <div className="space-y-2"><Label>Faol masofaviy talaba</Label><select disabled={!!editingId} className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.studentId} onChange={(e) => setForm({ ...form, studentId: Number(e.target.value) })}><option value={0}>Talabani tanlang</option>{(students.data ?? []).map((s) => <option key={s.id} value={s.id}>{s.studentNumber} - {s.fullName}</option>)}</select></div>
      <div className="space-y-2"><Label>O'quv yili</Label><Input value={form.academicYear} onChange={(e) => setForm({ ...form, academicYear: e.target.value })} /></div>
      <div className="space-y-2"><Label>Ta'til maqsadi</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.leavePurpose} onChange={(e) => setForm({ ...form, leavePurpose: e.target.value as AssessmentLeavePurpose })}>{Object.entries(purposeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
      <div className="space-y-2"><Label>Baholash/himoya rekviziti</Label><Input value={form.assessmentReference} onChange={(e) => setForm({ ...form, assessmentReference: e.target.value })} placeholder="Jadval, DAK yoki himoya buyrug'i" /></div>
      <div className="space-y-2"><Label>Ish beruvchi</Label><Input value={form.employerName} onChange={(e) => setForm({ ...form, employerName: e.target.value })} /></div>
      <div className="space-y-2"><Label>Lavozim</Label><Input value={form.jobTitle} onChange={(e) => setForm({ ...form, jobTitle: e.target.value })} /></div>
      <div className="space-y-2 md:col-span-2"><Label>Mehnat faoliyati dalili</Label><Input value={form.employmentDocumentReference} onChange={(e) => setForm({ ...form, employmentDocumentReference: e.target.value })} placeholder="Mehnat shartnomasi yoki elektron mehnat daftarchasi rekviziti" /></div>
      <div className="space-y-2"><Label>Ta'til buyrug'i raqami</Label><Input value={form.leaveOrderNumber} onChange={(e) => setForm({ ...form, leaveOrderNumber: e.target.value })} /></div>
      <div className="space-y-2"><Label>Buyruq sanasi</Label><Input type="date" max={localDate()} value={form.leaveOrderDate} onChange={(e) => setForm({ ...form, leaveOrderDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>Ta'til boshlanishi</Label><Input type="date" value={form.leaveStartDate} onChange={(e) => setForm({ ...form, leaveStartDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>Ta'til tugashi</Label><Input type="date" value={form.leaveEndDate} onChange={(e) => setForm({ ...form, leaveEndDate: e.target.value })} /><p className={`text-xs ${days >= 15 ? "text-emerald-700" : "text-amber-700"}`}>{days} kalendar kun</p></div>
      <label className="flex items-center gap-2 rounded-md border p-3 text-sm md:col-span-2"><input type="checkbox" checked={form.salaryRetentionConfirmed} onChange={(e) => setForm({ ...form, salaryRetentionConfirmed: e.target.checked })} />Ish beruvchi buyrug'ida ish haqi saqlanishi aniq ko'rsatilgan</label>
      <div className="space-y-2 md:col-span-2"><Label>Ta'til hujjati dalil rekviziti</Label><Input value={form.evidenceReference} onChange={(e) => setForm({ ...form, evidenceReference: e.target.value })} placeholder="Himoyalangan arxiv identifikatori yoki rasmiy hujjat rekviziti" /></div>
      {error && <p className="text-sm text-amber-700 md:col-span-2">{error}</p>}<div className="flex gap-2 md:col-span-2"><Button disabled={!!error || save.isPending} onClick={() => save.mutate()}>{editingId ? <Pencil className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{editingId ? "Saqlash" : "Qoralama yaratish"}</Button>{editingId && <Button variant="outline" onClick={() => { setEditingId(null); setForm(initialForm()); }}>Bekor qilish</Button>}</div>
    </CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{(records.data ?? []).map((record) => <Card key={record.id} className={record.status === "VERIFIED" ? "border-emerald-400" : record.status === "REJECTED" ? "border-red-300" : ""}><CardHeader><div className="flex justify-between gap-3"><div><CardTitle className="text-lg">{record.studentName}</CardTitle><CardDescription>{record.studentNumber} · {purposeLabel[record.leavePurpose]} · {record.academicYear}</CardDescription></div><Badge variant={record.status === "REJECTED" ? "destructive" : "secondary"}>{record.status}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-sm"><b>{record.employerName}</b> · {record.jobTitle}<br/>{record.leaveStartDate} — {record.leaveEndDate} · <b>{record.calendarDays} kun</b></p><p className="rounded-md bg-muted p-3 text-sm"><b>Buyruq:</b> {record.leaveOrderNumber}, {record.leaveOrderDate}<br/><b>Ish haqi saqlanadi:</b> {record.salaryRetentionConfirmed ? "Ha" : "Yo'q"}<br/><b>Dalil:</b> {record.evidenceReference}</p>{record.verificationNote && <p className="text-sm text-emerald-700"><BadgeCheck className="mr-1 inline h-4 w-4" />{record.verificationNote} · {record.verifiedByName}</p>}{record.rejectionReason && <p className="text-sm text-red-700">Rad etildi: {record.rejectionReason}</p>}<div className="flex flex-wrap gap-2">{canWrite && record.status === "DRAFT" && <><Button size="sm" variant="outline" onClick={() => edit(record)}><Pencil className="mr-1 h-3 w-3" />Tahrirlash</Button><Button size="sm" disabled={!record.salaryRetentionConfirmed} onClick={() => openReview(record, "verify")}><BadgeCheck className="mr-1 h-3 w-3" />Tekshirish</Button><Button size="sm" variant="destructive" onClick={() => openReview(record, "reject")}><XCircle className="mr-1 h-3 w-3" />Rad etish</Button></>}</div></CardContent></Card>)}{records.data?.length === 0 && <Card className="lg:col-span-2"><CardContent className="py-10 text-center text-muted-foreground">Ta'til dalili hali kiritilmagan.</CardContent></Card>}</div>
    <Dialog open={!!reviewing} onOpenChange={(open) => { if (!open) setReviewing(null); }}><DialogContent><DialogHeader><DialogTitle>{reviewMode === "verify" ? "Ta'til dalilini tekshirish" : "Ta'til dalilini rad etish"}</DialogTitle><DialogDescription>Muallifdan boshqa vakolatli foydalanuvchi ish beruvchi hujjatining asl mazmuni va rekvizitlarini tekshiradi.</DialogDescription></DialogHeader><div className="space-y-2"><Label>{reviewMode === "verify" ? "Tekshiruv izohi" : "Rad etish sababi"}</Label><Textarea value={reviewText} onChange={(e) => setReviewText(e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setReviewing(null)}>Bekor qilish</Button><Button variant={reviewMode === "reject" ? "destructive" : "default"} disabled={reviewText.trim().length < 10 || review.isPending} onClick={() => review.mutate()}>{reviewMode === "verify" ? "Tekshirish" : "Rad etish"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
