import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive as ArchiveIcon, Pencil, Plus, ShieldAlert, Upload, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/auth-context";
import { useToast } from "@/hooks/use-toast";
import { hasAuthority } from "@/lib/rbac-api";
import { distanceProgramRestrictionApi, distanceRestrictionInputError, type DistanceProgramRestrictionCatalog, type DistanceProgramRestrictionEntryInput, type DistanceRestrictionDegreeLevel, type SaveDistanceProgramRestrictionCatalogInput } from "@/services/api/distance-program-restriction-api";

const localDate = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); };
const emptyEntry = (): DistanceProgramRestrictionEntryInput => ({ programCode: "", programName: "", degreeLevel: "BACHELOR", reason: "" });
const emptyForm = (): SaveDistanceProgramRestrictionCatalogInput => { const year = new Date().getFullYear(); return { catalogYear: year, versionCode: `${year}-1`, authorityName: "Oliy ta'lim, fan va innovatsiyalar vazirligi", documentNumber: "", documentDate: localDate(), publicationDate: `${year}-04-01`, documentReference: "", scopeNote: "", entries: [] }; };

export function AdminDistanceProgramRestrictions() {
  const { user } = useAuth(); const canWrite = hasAuthority(user, "ACADEMIC_WRITE"); const { toast } = useToast(); const client = useQueryClient();
  const [form, setForm] = useState<SaveDistanceProgramRestrictionCatalogInput>(emptyForm); const [editingId, setEditingId] = useState<number | null>(null);
  const [entry, setEntry] = useState<DistanceProgramRestrictionEntryInput>(emptyEntry); const [publishing, setPublishing] = useState<DistanceProgramRestrictionCatalog | null>(null); const [verificationNote, setVerificationNote] = useState("");
  const catalogs = useQuery({ queryKey: ["distance-program-restrictions"], queryFn: distanceProgramRestrictionApi.list });
  const refresh = () => client.invalidateQueries({ queryKey: ["distance-program-restrictions"] });
  const fail = (error: Error) => toast({ variant: "destructive", title: "Amal bajarilmadi", description: error.message });
  const save = useMutation({ mutationFn: () => editingId ? distanceProgramRestrictionApi.update(editingId, form) : distanceProgramRestrictionApi.create(form), onSuccess: async () => { setEditingId(null); setForm(emptyForm()); setEntry(emptyEntry()); await refresh(); toast({ title: "Yillik katalog qoralamasi saqlandi" }); }, onError: fail });
  const publish = useMutation({ mutationFn: () => distanceProgramRestrictionApi.publish(publishing!.id, verificationNote), onSuccess: async () => { setPublishing(null); setVerificationNote(""); await refresh(); toast({ title: "Rasmiy katalog e'lon qilingan deb qayd etildi" }); }, onError: fail });
  const archive = useMutation({ mutationFn: (id: number) => distanceProgramRestrictionApi.archive(id), onSuccess: async () => { await refresh(); toast({ title: "Katalog arxivlandi" }); }, onError: fail });
  const addEntry = () => { if (!entry.programCode.trim() || entry.programName.trim().length < 3 || entry.reason.trim().length < 5) return; setForm({ ...form, entries: [...form.entries, { ...entry, programCode: entry.programCode.trim().toUpperCase() }] }); setEntry(emptyEntry()); };
  const edit = (catalog: DistanceProgramRestrictionCatalog) => { setEditingId(catalog.id); setForm({ catalogYear: catalog.catalogYear, versionCode: catalog.versionCode, authorityName: catalog.authorityName, documentNumber: catalog.documentNumber, documentDate: catalog.documentDate, publicationDate: catalog.publicationDate, documentReference: catalog.documentReference, scopeNote: catalog.scopeNote, entries: catalog.entries.map(({ programCode, programName, degreeLevel, reason }) => ({ programCode, programName, degreeLevel, reason })) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const error = distanceRestrictionInputError(form);

  return <div className="space-y-6 p-3 sm:p-6">
    <div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldAlert className="h-6 w-6" />Taqiqlangan masofaviy yo'nalishlar</h1><p className="text-sm text-muted-foreground">559-son qaror 14-bandi bo'yicha vakolatli vazirlik har yili 1-aprelgacha e'lon qiladigan rasmiy ro'yxat. LMS ro'yxat mazmunini o'zi yaratmaydi.</p></div>
    {canWrite && <Card><CardHeader><CardTitle>{editingId ? "Katalog qoralamasini tahrirlash" : "Yillik rasmiy katalog qoralamasi"}</CardTitle><CardDescription>Faqat qayta ochiladigan rasmiy hujjat va e'lon rekvizitidan ko'chiring. Bo'sh ro'yxat ham hujjatda hech bir taqiq yo'qligi aniq qayd etilgan bo'lsagina saqlanadi.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">
      <div className="space-y-2"><Label>Katalog yili</Label><Input type="number" min={2022} max={new Date().getFullYear() + 1} value={form.catalogYear} onChange={(e) => setForm({ ...form, catalogYear: Number(e.target.value) })} /></div><div className="space-y-2"><Label>Versiya kodi</Label><Input value={form.versionCode} onChange={(e) => setForm({ ...form, versionCode: e.target.value })} /></div>
      <div className="space-y-2 md:col-span-2"><Label>Vakolatli vazirlik</Label><Input value={form.authorityName} onChange={(e) => setForm({ ...form, authorityName: e.target.value })} /></div><div className="space-y-2"><Label>Hujjat raqami</Label><Input value={form.documentNumber} onChange={(e) => setForm({ ...form, documentNumber: e.target.value })} /></div><div className="space-y-2"><Label>Hujjat sanasi</Label><Input type="date" value={form.documentDate} onChange={(e) => setForm({ ...form, documentDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>E'lon sanasi</Label><Input type="date" value={form.publicationDate} onChange={(e) => setForm({ ...form, publicationDate: e.target.value })} /></div><div className="space-y-2"><Label>Rasmiy hujjat/e'lon rekviziti</Label><Input value={form.documentReference} onChange={(e) => setForm({ ...form, documentReference: e.target.value })} /></div><div className="space-y-2 md:col-span-2"><Label>Qamrov izohi</Label><Textarea value={form.scopeNote} onChange={(e) => setForm({ ...form, scopeNote: e.target.value })} /></div>
      <div className="space-y-3 rounded-md border p-3 md:col-span-2"><div><Label>Taqiqlangan yo'nalish yozuvi</Label><p className="text-xs text-muted-foreground">Rasmiy ro'yxatdagi kod, nom, daraja va asosni aynan kiriting.</p></div><div className="grid gap-2 md:grid-cols-2"><Input value={entry.programCode} onChange={(e) => setEntry({ ...entry, programCode: e.target.value.toUpperCase() })} placeholder="Yo'nalish kodi" /><Input value={entry.programName} onChange={(e) => setEntry({ ...entry, programName: e.target.value })} placeholder="Yo'nalish nomi" /><select className="h-10 rounded-md border bg-background px-3 text-sm" value={entry.degreeLevel} onChange={(e) => setEntry({ ...entry, degreeLevel: e.target.value as DistanceRestrictionDegreeLevel })}><option value="BACHELOR">Bakalavriat</option><option value="MASTER">Magistratura</option></select><Input value={entry.reason} onChange={(e) => setEntry({ ...entry, reason: e.target.value })} placeholder="Taqiqlash asosi" /></div><Button type="button" variant="outline" onClick={addEntry}><Plus className="mr-2 h-4 w-4" />Ro'yxatga qo'shish</Button>
      <div className="space-y-2">{form.entries.map((item, index) => <div key={`${item.programCode}-${item.degreeLevel}-${index}`} className="flex items-start justify-between rounded-md bg-muted p-2 text-sm"><span><b>{item.programCode}</b> — {item.programName} ({item.degreeLevel})<br/><span className="text-xs text-muted-foreground">{item.reason}</span></span><Button size="icon" variant="ghost" onClick={() => setForm({ ...form, entries: form.entries.filter((_, itemIndex) => itemIndex !== index) })}><X className="h-4 w-4" /></Button></div>)}</div></div>
      {error && <p className="text-sm text-amber-700 md:col-span-2">{error}</p>}<div className="flex gap-2 md:col-span-2"><Button disabled={!!error || save.isPending} onClick={() => save.mutate()}>{editingId ? <Pencil className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{editingId ? "Saqlash" : "Qoralama yaratish"}</Button>{editingId && <Button variant="outline" onClick={() => { setEditingId(null); setForm(emptyForm()); }}>Bekor qilish</Button>}</div>
    </CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{(catalogs.data ?? []).map((catalog) => <Card key={catalog.id} className={catalog.status === "PUBLISHED" ? catalog.deadlineCompliant ? "border-emerald-400" : "border-amber-500" : ""}><CardHeader><div className="flex justify-between gap-3"><div><CardTitle className="text-lg">{catalog.catalogYear} · {catalog.versionCode}</CardTitle><CardDescription>{catalog.authorityName} · {catalog.documentNumber}</CardDescription></div><Badge variant={catalog.status === "ARCHIVED" ? "outline" : "secondary"}>{catalog.status}</Badge></div></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Hujjat:</b> {catalog.documentDate}<br/><b>E'lon:</b> {catalog.publicationDate} (deadline {catalog.publicationDeadline})<br/><b>Rekvizit:</b> {catalog.documentReference}</p><p className={catalog.deadlineCompliant ? "text-emerald-700" : "text-amber-700"}>{catalog.deadlineCompliant ? "1-aprel deadline'iga mos" : "1-aprel deadline'idan kech e'lon qilingan"}</p><div className="rounded-md bg-muted p-3"><b>Qamrov:</b> {catalog.scopeNote}<br/><b>Taqiqlangan yozuvlar:</b> {catalog.entries.length}</div>{catalog.entries.map((item) => <div key={item.id} className="rounded-md border p-2"><b>{item.programCode}</b> — {item.programName} ({item.degreeLevel})<br/>{item.reason}</div>)}{catalog.verificationNote && <p><b>Mustaqil tekshiruv:</b> {catalog.verificationNote} — {catalog.publishedByName}</p>}
      {canWrite && catalog.status === "DRAFT" && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => edit(catalog)}><Pencil className="mr-1 h-3 w-3" />Tahrirlash</Button><Button size="sm" onClick={() => { setPublishing(catalog); setVerificationNote(""); }}><Upload className="mr-1 h-3 w-3" />E'lonni tasdiqlash</Button></div>}{canWrite && catalog.status === "PUBLISHED" && <Button size="sm" variant="outline" disabled={archive.isPending} onClick={() => archive.mutate(catalog.id)}><ArchiveIcon className="mr-1 h-3 w-3" />Arxivlash</Button>}
    </CardContent></Card>)}{catalogs.data?.length === 0 && <Card className="lg:col-span-2"><CardContent className="py-10 text-center text-red-700">Joriy rasmiy katalog yo'q. Yangi masofaviy dastur, qabul siyosati va qabul fail-closed bloklanadi.</CardContent></Card>}</div>
    <Dialog open={!!publishing} onOpenChange={(open) => { if (!open) setPublishing(null); }}><DialogContent><DialogHeader><DialogTitle>Rasmiy e'lonni mustaqil tasdiqlash</DialogTitle><DialogDescription>Muallifdan boshqa vakolatli xodim hujjat raqami, e'lon sanasi, manba va barcha kodlarni rasmiy nashrga solishtiradi.</DialogDescription></DialogHeader><div className="space-y-2"><Label>Tekshiruv izohi</Label><Textarea value={verificationNote} onChange={(e) => setVerificationNote(e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setPublishing(null)}>Bekor qilish</Button><Button disabled={verificationNote.trim().length < 10 || publish.isPending} onClick={() => publish.mutate()}>Tasdiqlash</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
