import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Globe2, Pencil, Plus, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/auth-context";
import { useToast } from "@/hooks/use-toast";
import { hasAuthority } from "@/lib/rbac-api";
import { foreignTeacherEngagementApi, foreignTeacherEngagementInputError, type ForeignTeacherEngagement, type SaveForeignTeacherEngagementInput } from "@/services/api/foreign-teacher-engagement-api";

const localDate = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); };
const currentAcademicYear = () => { const date = new Date(); const first = date.getMonth() >= 8 ? date.getFullYear() : date.getFullYear() - 1; return `${first}-${first + 1}`; };
const initialForm = (): SaveForeignTeacherEngagementInput => ({ teacherId: 0, academicYear: currentAcademicYear(), citizenshipCountryCode: "", citizenshipEvidenceReference: "", qualificationReference: "", contractNumber: "", contractDate: localDate(), engagementOrderNumber: "", engagementOrderDate: localDate(), engagementStartDate: "", engagementEndDate: "", remoteTeachingConfirmed: false, evidenceReference: "", courseIds: [] });

export function AdminForeignTeacherEngagements() {
  const { user } = useAuth(); const canWrite = hasAuthority(user, "TEACHER_WRITE"); const { toast } = useToast(); const client = useQueryClient();
  const [form, setForm] = useState<SaveForeignTeacherEngagementInput>(initialForm); const [editingId, setEditingId] = useState<number | null>(null);
  const [reviewing, setReviewing] = useState<ForeignTeacherEngagement | null>(null); const [reviewMode, setReviewMode] = useState<"verify" | "reject">("verify"); const [reviewText, setReviewText] = useState("");
  const records = useQuery({ queryKey: ["foreign-teacher-engagements"], queryFn: foreignTeacherEngagementApi.list });
  const teachers = useQuery({ queryKey: ["foreign-teacher-engagements", "teachers"], queryFn: foreignTeacherEngagementApi.eligibleTeachers, enabled: canWrite });
  const courses = useQuery({ queryKey: ["foreign-teacher-engagements", "courses"], queryFn: foreignTeacherEngagementApi.eligibleCourses, enabled: canWrite });
  const refresh = () => client.invalidateQueries({ queryKey: ["foreign-teacher-engagements"] });
  const fail = (error: Error) => toast({ variant: "destructive", title: "Amal bajarilmadi", description: error.message });
  const save = useMutation({ mutationFn: () => editingId ? foreignTeacherEngagementApi.update(editingId, form) : foreignTeacherEngagementApi.create(form), onSuccess: async () => { setEditingId(null); setForm(initialForm()); await refresh(); toast({ title: "Xorijiy pedagog engagement qoralamasi saqlandi" }); }, onError: fail });
  const review = useMutation({ mutationFn: () => reviewMode === "verify" ? foreignTeacherEngagementApi.verify(reviewing!.id, reviewText) : foreignTeacherEngagementApi.reject(reviewing!.id, reviewText), onSuccess: async () => { setReviewing(null); setReviewText(""); await refresh(); toast({ title: "Engagement holati yangilandi" }); }, onError: fail });
  const toggleCourse = (id: number) => setForm({ ...form, courseIds: form.courseIds.includes(id) ? form.courseIds.filter((value) => value !== id) : [...form.courseIds, id] });
  const edit = (record: ForeignTeacherEngagement) => { setEditingId(record.id); setForm({ teacherId: record.teacherId, academicYear: record.academicYear, citizenshipCountryCode: record.citizenshipCountryCode, citizenshipEvidenceReference: record.citizenshipEvidenceReference, qualificationReference: record.qualificationReference, contractNumber: record.contractNumber, contractDate: record.contractDate, engagementOrderNumber: record.engagementOrderNumber, engagementOrderDate: record.engagementOrderDate, engagementStartDate: record.engagementStartDate, engagementEndDate: record.engagementEndDate, remoteTeachingConfirmed: record.remoteTeachingConfirmed, evidenceReference: record.evidenceReference, courseIds: record.courses.map((course) => course.id) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openReview = (record: ForeignTeacherEngagement, mode: "verify" | "reject") => { setReviewing(record); setReviewMode(mode); setReviewText(""); };
  const error = foreignTeacherEngagementInputError(form, localDate());

  return <div className="space-y-6 p-3 sm:p-6">
    <div><h1 className="text-2xl font-bold">Xorijiy pedagoglar</h1><p className="text-sm text-muted-foreground">559-son qaror 25-bandi bo'yicha masofadan dars olib boradigan xorijiy pedagogni jalb qilish dalillari.</p></div>
    {canWrite && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 className="h-5 w-5" />{editingId ? "Qoralamani tahrirlash" : "Xorijiy pedagog engagementi"}</CardTitle><CardDescription>Fuqarolik va malaka dalili, shartnoma, buyruq, davr hamda masofaviy kurslar bir yozuvda tekshiriladi.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">
      <div className="space-y-2"><Label>Faol pedagog</Label><select disabled={!!editingId} className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.teacherId} onChange={(e) => setForm({ ...form, teacherId: Number(e.target.value) })}><option value={0}>Pedagogni tanlang</option>{(teachers.data ?? []).map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.fullName}{teacher.academicDegree ? ` - ${teacher.academicDegree}` : ""}</option>)}</select></div>
      <div className="space-y-2"><Label>O'quv yili</Label><Input value={form.academicYear} onChange={(e) => setForm({ ...form, academicYear: e.target.value })} /></div>
      <div className="space-y-2"><Label>Fuqarolik davlati kodi</Label><Input maxLength={2} value={form.citizenshipCountryCode} onChange={(e) => setForm({ ...form, citizenshipCountryCode: e.target.value.toUpperCase() })} placeholder="ISO alpha-2, masalan IL" /></div>
      <div className="space-y-2"><Label>Fuqarolik dalili rekviziti</Label><Input value={form.citizenshipEvidenceReference} onChange={(e) => setForm({ ...form, citizenshipEvidenceReference: e.target.value })} /></div>
      <div className="space-y-2 md:col-span-2"><Label>Malaka hujjati rekviziti</Label><Input value={form.qualificationReference} onChange={(e) => setForm({ ...form, qualificationReference: e.target.value })} /></div>
      <div className="space-y-2"><Label>Shartnoma raqami</Label><Input value={form.contractNumber} onChange={(e) => setForm({ ...form, contractNumber: e.target.value })} /></div>
      <div className="space-y-2"><Label>Shartnoma sanasi</Label><Input type="date" max={localDate()} value={form.contractDate} onChange={(e) => setForm({ ...form, contractDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>Jalb qilish buyrug'i</Label><Input value={form.engagementOrderNumber} onChange={(e) => setForm({ ...form, engagementOrderNumber: e.target.value })} /></div>
      <div className="space-y-2"><Label>Buyruq sanasi</Label><Input type="date" max={localDate()} value={form.engagementOrderDate} onChange={(e) => setForm({ ...form, engagementOrderDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>Engagement boshlanishi</Label><Input type="date" value={form.engagementStartDate} onChange={(e) => setForm({ ...form, engagementStartDate: e.target.value })} /></div>
      <div className="space-y-2"><Label>Engagement tugashi</Label><Input type="date" value={form.engagementEndDate} onChange={(e) => setForm({ ...form, engagementEndDate: e.target.value })} /></div>
      <div className="space-y-2 md:col-span-2"><Label>Faol masofaviy dastur kurslari</Label><div className="grid max-h-48 gap-2 overflow-auto rounded-md border p-3 sm:grid-cols-2">{(courses.data ?? []).map((course) => <label key={course.id} className="flex gap-2 text-sm"><input type="checkbox" checked={form.courseIds.includes(course.id)} onChange={() => toggleCourse(course.id)} /><span><b>{course.title}</b><br/><span className="text-xs text-muted-foreground">{course.subjectName} - {course.programName}</span></span></label>)}{courses.data?.length === 0 && <p className="text-sm text-muted-foreground">Mos masofaviy kurs topilmadi.</p>}</div></div>
      <label className="flex items-center gap-2 rounded-md border p-3 text-sm md:col-span-2"><input type="checkbox" checked={form.remoteTeachingConfirmed} onChange={(e) => setForm({ ...form, remoteTeachingConfirmed: e.target.checked })} />Shartnoma yoki buyruqda darslar masofadan olib borilishi ko'rsatilgan</label>
      <div className="space-y-2 md:col-span-2"><Label>Himoyalangan engagement dalili</Label><Input value={form.evidenceReference} onChange={(e) => setForm({ ...form, evidenceReference: e.target.value })} placeholder="HR arxiv identifikatori yoki rasmiy hujjat rekviziti" /></div>
      {error && <p className="text-sm text-amber-700 md:col-span-2">{error}</p>}<div className="flex gap-2 md:col-span-2"><Button disabled={!!error || save.isPending} onClick={() => save.mutate()}>{editingId ? <Pencil className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{editingId ? "Saqlash" : "Qoralama yaratish"}</Button>{editingId && <Button variant="outline" onClick={() => { setEditingId(null); setForm(initialForm()); }}>Bekor qilish</Button>}</div>
    </CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{(records.data ?? []).map((record) => <Card key={record.id} className={record.status === "VERIFIED" ? "border-emerald-400" : record.status === "REJECTED" ? "border-red-300" : ""}><CardHeader><div className="flex justify-between gap-3"><div><CardTitle className="text-lg">{record.teacherName}</CardTitle><CardDescription>{record.citizenshipCountryCode} - {record.academicYear} - {record.engagementStartDate} / {record.engagementEndDate}</CardDescription></div><Badge variant={record.status === "REJECTED" ? "destructive" : "secondary"}>{record.status}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-sm"><b>Shartnoma:</b> {record.contractNumber}, {record.contractDate}<br/><b>Buyruq:</b> {record.engagementOrderNumber}, {record.engagementOrderDate}<br/><b>Masofaviy dars:</b> {record.remoteTeachingConfirmed ? "Tasdiqlangan" : "Tasdiqlanmagan"}</p><div className="rounded-md bg-muted p-3 text-sm"><b>Kurslar:</b> {record.courses.map((course) => course.title).join(", ")}<br/><b>Dalil:</b> {record.evidenceReference}</div>{record.verificationNote && <p className="text-sm text-emerald-700"><BadgeCheck className="mr-1 inline h-4 w-4" />{record.verificationNote} - {record.verifiedBy}</p>}{record.rejectionReason && <p className="text-sm text-red-700">Rad etildi: {record.rejectionReason}</p>}{canWrite && record.status === "DRAFT" && <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => edit(record)}><Pencil className="mr-1 h-3 w-3" />Tahrirlash</Button><Button size="sm" disabled={!record.remoteTeachingConfirmed} onClick={() => openReview(record, "verify")}><BadgeCheck className="mr-1 h-3 w-3" />Tekshirish</Button><Button size="sm" variant="destructive" onClick={() => openReview(record, "reject")}><XCircle className="mr-1 h-3 w-3" />Rad etish</Button></div>}</CardContent></Card>)}{records.data?.length === 0 && <Card className="lg:col-span-2"><CardContent className="py-10 text-center text-muted-foreground">Xorijiy pedagog engagementi hali kiritilmagan. 25-band ruxsat beruvchi norma bo'lgani uchun bu holat violation hisoblanmaydi.</CardContent></Card>}</div>
    <Dialog open={!!reviewing} onOpenChange={(open) => { if (!open) setReviewing(null); }}><DialogContent><DialogHeader><DialogTitle>{reviewMode === "verify" ? "Engagementni tekshirish" : "Engagementni rad etish"}</DialogTitle><DialogDescription>Muallifdan boshqa vakolatli xodim xorijiy fuqarolik, malaka, shartnoma, buyruq va masofaviy kurs dalillarini tekshiradi.</DialogDescription></DialogHeader><div className="space-y-2"><Label>{reviewMode === "verify" ? "Tekshiruv izohi" : "Rad etish sababi"}</Label><Textarea value={reviewText} onChange={(e) => setReviewText(e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setReviewing(null)}>Bekor qilish</Button><Button variant={reviewMode === "reject" ? "destructive" : "default"} disabled={reviewText.trim().length < 10 || review.isPending} onClick={() => review.mutate()}>{reviewMode === "verify" ? "Tekshirish" : "Rad etish"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
