import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { ColumnDef } from "@tanstack/react-table";
import { Download, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  listElectiveExceptions,
  listInactiveStudents,
  listLearningParticipation,
  listLessonComments,
  listStudentIps,
  type ElectiveChoiceExceptionRow,
  type LearningParticipationRow,
  type LessonCommentReportRow,
  type StudentIpReportRow,
  type StudentLoginMonitorRow,
} from "@/services/api/monitoring-reports-api";

const ALL="__all__";
const date=(value?:string|null)=>value?new Date(value).toLocaleString("uz-Latn"):"Kirmagan";
function csv(filename:string,headers:string[],rows:Array<Array<unknown>>){const q=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const body=`\uFEFF${[headers,...rows].map(r=>r.map(q).join(",")).join("\r\n")}`;const url=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function Header({title,description,onExport}:{title:string;description:string;onExport?:()=>void}){return <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{onExport&&<Button variant="outline" onClick={onExport}><Download className="mr-2 h-4 w-4"/>Excel uchun CSV</Button>}</div>}
function State({loading,error,retry}:{loading:boolean;error:unknown;retry:()=>void}){if(loading)return <Card><CardContent className="p-10 text-center text-sm text-muted-foreground">Yuklanmoqda...</CardContent></Card>;if(error)return <Card className="border-destructive"><CardContent className="space-y-3 p-10 text-center"><p className="text-sm text-destructive">{error instanceof Error?error.message:"Ma'lumot yuklanmadi"}</p><Button variant="outline" onClick={retry}><RefreshCw className="mr-2 h-4 w-4"/>Qayta urinish</Button></CardContent></Card>;return null;}
function Filter({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <div className="min-w-40 space-y-1"><Label className="text-xs">{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ALL}>Barchasi</SelectItem>{values.filter(Boolean).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>}

export function InactiveStudentMonitoring(){
  const [days,setDays]=useState("7");const query=useQuery({queryKey:["inactive-students",days],queryFn:()=>listInactiveStudents(Number(days)),staleTime:30_000});const rows=query.data??[];
  const columns:ColumnDef<StudentLoginMonitorRow>[]=[{accessorKey:"fullName",header:"F.I.O."},{accessorKey:"group",header:"Guruh"},{id:"login",header:"Login sanasi",cell:({row})=>date(row.original.lastLoginAt)},{id:"inactive",header:"Faol emas",cell:({row})=>row.original.inactiveDays==null?"Hech kirmagan":`${row.original.inactiveDays} kun`}];
  return <div className="space-y-6 p-3 sm:p-6"><Header title="Darsga qatnashmayotgan talabalar ro'yxati" description="Oxirgi login sanasi tanlangan muddatdan eski yoki hech kirmagan faol talabalar." onExport={()=>csv("inactive-students.csv",["F.I.O.","Guruh","Login","Faol emas kun"],rows.map(r=>[r.fullName,r.group,r.lastLoginAt,r.inactiveDays]))}/><div className="w-52 space-y-1"><Label className="text-xs">Faolsizlik muddati</Label><Select value={days} onValueChange={setDays}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[7,14,30,60,90].map(v=><SelectItem key={v} value={String(v)}>{v} kun</SelectItem>)}</SelectContent></Select></div><State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{!query.isLoading&&!query.error&&<DataTable columns={columns} data={rows} searchPlaceholder="F.I.O. bo'yicha qidirish..." emptyText="Ma'lumot mavjud emas"/>}</div>;
}

export function ElectiveChoiceMonitoring(){
  const [status,setStatus]=useState(ALL),[year,setYear]=useState(ALL),[program,setProgram]=useState(ALL),[semester,setSemester]=useState(ALL),[subject,setSubject]=useState(ALL),[group,setGroup]=useState(ALL);const query=useQuery({queryKey:["elective-exceptions"],queryFn:listElectiveExceptions,staleTime:30_000});const rows=query.data??[];const vals=(f:(r:ElectiveChoiceExceptionRow)=>string)=>[...new Set(rows.map(f).filter(Boolean))].sort();const filtered=rows.filter(r=>(status===ALL||r.status===status)&&(year===ALL||r.academicYear===year)&&(program===ALL||r.curriculum===program)&&(semester===ALL||String(r.semester)===semester)&&(subject===ALL||r.subject===subject)&&(group===ALL||r.group===group));
  const columns:ColumnDef<ElectiveChoiceExceptionRow>[]=[{accessorKey:"fullName",header:"F.I.O."},{accessorKey:"curriculum",header:"O'quv reja"},{accessorKey:"group",header:"Guruh"},{accessorKey:"subject",header:"Fan"},{accessorKey:"semester",header:"Semestr"},{id:"status",header:"Holati",cell:({row})=><Badge variant="destructive">{row.original.status}</Badge>}];
  return <div className="space-y-6 p-3 sm:p-6"><Header title="Tanlov fanlari" description="Mavjud ixtiyoriy fan kontekstida fanni tanlamagan faol talabalar." onExport={()=>csv("elective-exceptions.csv",["F.I.O.","Reja","Guruh","Fan","Yil","Semestr","Holat"],filtered.map(r=>[r.fullName,r.curriculum,r.group,r.subject,r.academicYear,r.semester,r.status]))}/><div className="flex flex-wrap gap-3 rounded-lg border p-4"><Filter label="Status" value={status} values={vals(r=>r.status)} onChange={setStatus}/><Filter label="O'quv yili" value={year} values={vals(r=>r.academicYear)} onChange={setYear}/><Filter label="O'quv dasturi" value={program} values={vals(r=>r.curriculum)} onChange={setProgram}/><Filter label="Semestr" value={semester} values={vals(r=>String(r.semester))} onChange={setSemester}/><Filter label="Fan" value={subject} values={vals(r=>r.subject)} onChange={setSubject}/><Filter label="Guruh" value={group} values={vals(r=>r.group)} onChange={setGroup}/></div><State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{!query.isLoading&&!query.error&&<DataTable columns={columns} data={filtered} searchPlaceholder="F.I.O. bo'yicha qidirish..." emptyText="Ma'lumot mavjud emas"/>}</div>;
}

export function LearningParticipationMonitoring(){
  const query=useQuery({queryKey:["learning-participation"],queryFn:listLearningParticipation,staleTime:30_000});const rows=query.data??[];const columns:ColumnDef<LearningParticipationRow>[]=[{accessorKey:"fullName",header:"F.I.O."},{accessorKey:"group",header:"Guruh"},{accessorKey:"program",header:"O'quv dasturi"},{accessorKey:"lesson",header:"Dars nomi"},{id:"login",header:"Login sanasi",cell:({row})=>date(row.original.loginDate)},{id:"event",header:"Faollik",cell:({row})=><Badge variant="outline">{row.original.eventType}</Badge>},{id:"duration",header:"Davomiylik",cell:({row})=>`${row.original.durationSeconds} soniya`}];
  return <div className="space-y-6 p-3 sm:p-6"><Header title="Talabalarning fanlarda ishtiroki" description="Kontent, SCORM, test va mashg'ulot bo'yicha haqiqiy o'quv faolligi." onExport={()=>csv("learning-participation.csv",["F.I.O.","Guruh","Dastur","Dars","Faollik","Sana","Soniya"],rows.map(r=>[r.fullName,r.group,r.program,r.lesson,r.eventType,r.loginDate,r.durationSeconds]))}/><State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{!query.isLoading&&!query.error&&<DataTable columns={columns} data={rows} searchPlaceholder="Talaba yoki dars bo'yicha qidirish..." emptyText="Ma'lumot mavjud emas"/>}</div>;
}

export function StudentIpMonitoring(){
  const [group,setGroup]=useState(ALL);const query=useQuery({queryKey:["student-ips"],queryFn:listStudentIps,staleTime:30_000});const rows=query.data??[];const groups=[...new Set(rows.map(r=>r.group).filter(Boolean))].sort();const filtered=rows.filter(r=>group===ALL||r.group===group);const columns:ColumnDef<StudentIpReportRow>[]=[{accessorKey:"fullName",header:"F.I.O."},{accessorKey:"group",header:"Guruh"},{accessorKey:"username",header:"Login"},{id:"ips",header:"IP manzillar",cell:({row})=><div className="flex flex-wrap gap-1">{row.original.ipAddresses.map(ip=><Badge variant="outline" key={ip}>{ip}</Badge>)}</div>},{accessorKey:"loginCount",header:"Kirishlar"},{id:"last",header:"Oxirgi kirish",cell:({row})=>date(row.original.lastSeenAt)}];
  return <div className="space-y-6 p-3 sm:p-6"><Header title="Talabalarning IP manzillarini tekshirish" description="Muvaffaqiyatli login auditidan guruhlangan IP manzillar va oxirgi kirish." onExport={()=>csv("student-ips.csv",["F.I.O.","Guruh","Login","IP","Kirishlar","Oxirgi"],filtered.map(r=>[r.fullName,r.group,r.username,r.ipAddresses.join(";"),r.loginCount,r.lastSeenAt]))}/><div className="max-w-64"><Filter label="Guruh" value={group} values={groups} onChange={setGroup}/></div><State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{!query.isLoading&&!query.error&&<DataTable columns={columns} data={filtered} searchPlaceholder="F.I.O. bo'yicha qidirish..." emptyText="Ma'lumot mavjud emas"/>}</div>;
}

export function LessonCommentMonitoring(){
  const [year,setYear]=useState(ALL),[program,setProgram]=useState(ALL),[semester,setSemester]=useState(ALL),[course,setCourse]=useState(ALL);const query=useQuery({queryKey:["lesson-comments"],queryFn:listLessonComments,staleTime:30_000});const rows=query.data??[];const vals=(f:(r:LessonCommentReportRow)=>string)=>[...new Set(rows.map(f).filter(Boolean))].sort();const filtered=rows.filter(r=>(year===ALL||r.academicYear===year)&&(program===ALL||r.program===program)&&(semester===ALL||String(r.semester??"")===semester)&&(course===ALL||r.course===course));const columns:ColumnDef<LessonCommentReportRow>[]=[{accessorKey:"course",header:"Fan"},{accessorKey:"topic",header:"Mavzu"},{accessorKey:"author",header:"Muallif"},{accessorKey:"comment",header:"Izoh"},{id:"date",header:"Sana",cell:({row})=>date(row.original.createdAt)},{id:"status",header:"Holati",cell:({row})=><Badge variant={row.original.hidden?"destructive":"default"}>{row.original.hidden?"Yashirilgan":"Ko'rinadi"}</Badge>}];
  return <div className="space-y-6 p-3 sm:p-6"><Header title="Fanlardagi izohlar" description="Kurs forumlari va dars muhokamalaridagi izohlar monitoringi." onExport={()=>csv("lesson-comments.csv",["Yil","Dastur","Semestr","Fan","Mavzu","Muallif","Izoh","Sana","Yashirilgan"],filtered.map(r=>[r.academicYear,r.program,r.semester,r.course,r.topic,r.author,r.comment,r.createdAt,r.hidden]))}/><div className="flex flex-wrap gap-3 rounded-lg border p-4"><Filter label="O'quv yili" value={year} values={vals(r=>r.academicYear)} onChange={setYear}/><Filter label="O'quv dasturi" value={program} values={vals(r=>r.program)} onChange={setProgram}/><Filter label="Semestr" value={semester} values={vals(r=>String(r.semester??""))} onChange={setSemester}/><Filter label="Fan" value={course} values={vals(r=>r.course)} onChange={setCourse}/></div><State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>{!query.isLoading&&!query.error&&<DataTable columns={columns} data={filtered} searchPlaceholder="Izoh yoki muallif bo'yicha qidirish..." emptyText="Ma'lumot mavjud emas"/>}</div>;
}
